### ISSUE TITLE
thumbnail of the active tab is invisible if theme is light or dark

### ISSUE THREAD

**Issue by gomita** [gomita/visualtabs#1]
Need to fix z-index order of `.thumbnail`.

**Comment by grahamperrin** [comment]
Not reproducible with Waterfox Current 2019.10: 

![image](https://user-images.githubusercontent.com/192271/68538204-570a5b00-0368-11ea-95db-a446f30995ce.png)

**Comment by gomita** [comment]
Already fixed.
