### ISSUE TITLE
hotkey for toggle

### ISSUE THREAD

**Issue by WeiLiPenguin** [gomita/visualtabs#9]
Hi,
Firefox looks like do not have a hotkey for sidebar (only for history and bookmark).
Could you please add a hotkey option for toggle showing "visual tabs"
Thanks
Best Regards!

**Comment by gomita** [comment]
Thanks for your suggestion.
Which key is prefer to toggle Visual Tabs sidebar by default?

**Comment by WeiLiPenguin** [comment]
Hi,

How about F1 ?
Thanks!

**Comment by gomita** [comment]
ver.0.80 has been released.

**Comment by WeiLiPenguin** [comment]
Nice !
Great thanks!
BR!
